### PR TITLE
feat: Added support for Arrow Keys

### PR DESCRIPTION
**Pull request by thetejasmagade**
Added Support for Arrow keys like ArrowUp, ArrowDown, ArrowLeft, ArrowRight. (❁´◡`❁)
⬅️ ⬆️ ➡️ ⬇️

### CODE REVIEW

**Review by rogeriotaques — CHANGES_REQUESTED** [review]
LGTM! 🚀 
Thank you for the PR!

Nitpick: 
Can I suggest one little change, tho?
Would you mind adding `.parcel-cache` to `.gitignore`?

**Comment by thetejasmagade** [comment]
Yeah!, I just forgot about it.

**Comment by thetejasmagade** [comment]
@rogeriotaques I made changes

**Review by rogeriotaques — APPROVED** [review]
LGTM. 🎉

**Pull request merged**
