### PR TITLE
Improved Documentation Website 

### PR DESCRIPTION
**Pull request by thetejasmagade**
hey, @rogeriotaques sorry for the late..
Website is now ready. Tell me changes if you want.

See preview here
[https://dynamic-biscochitos-d8d357.netlify.app/](https://dynamic-biscochitos-d8d357.netlify.app/)

### CODE REVIEW

**Comment by thetejasmagade** [comment]
Hey, @rogeriotaques my friend can you please do that changes for me that you have mentioned. Please 🙏❤️

**Comment by rogeriotaques** [comment]
Sure, but it may take a while since I'm a bit short on time these days. 😓

**Comment by thetejasmagade** [comment]
I also have University exams and all that stuff 😂😂. But, don't worry I will try to do it.

**Comment by rogeriotaques** [comment]
Don't worry, mate!
University duties first, for sure. 💪🎓

**Comment by thetejasmagade** [comment]
Hey, @rogeriotaques made changes that you have mentioned

**Pull request merged**
